# Generated by Django 2.2.16 on 2022-04-07 21:49

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('file', models.FileField(upload_to='media/files')),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('version', models.CharField(default='', max_length=50)),
                ('build_no', models.CharField(default='', max_length=50)),
                ('branch', models.CharField(default='', max_length=255)),
                ('status', models.IntegerField(default=1)),
                ('file', models.ForeignKey(default=1, on_delete=django.db.models.expressions.Case, to='packageAnalyse.UploadFile')),
            ],
            options={
                'verbose_name': '版本发布记录表',
                'verbose_name_plural': '版本发布记录表',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('module_name', models.CharField(default='', max_length=50)),
                ('module_size', models.IntegerField(default=0)),
                ('module_type', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('publish', models.ManyToManyField(default=0, to='packageAnalyse.Publish')),
            ],
            options={
                'verbose_name': '模块大小记录表',
                'verbose_name_plural': '模块大小记录表',
                'ordering': ['-id'],
            },
        ),
    ]
