# Generated by Django 2.2.16 on 2022-03-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('version', models.CharField(default='', max_length=50)),
                ('build_no', models.CharField(default='', max_length=50)),
                ('branch', models.CharField(default='', max_length=255)),
                ('result', models.TextField(default='')),
                ('status', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': '版本发布记录表',
                'verbose_name_plural': '版本发布记录表',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, auto_now=True)),
                ('module_name', models.CharField(default='', max_length=50)),
                ('module_size', models.IntegerField(default=0)),
                ('module_type', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('publish', models.ManyToManyField(default=0, to='packageAnalyse.Publish')),
            ],
            options={
                'verbose_name': '模块大小记录表',
                'verbose_name_plural': '模块大小记录表',
            },
        ),
    ]
