# Generated by Django 2.2.16 on 2022-04-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packageAnalyse', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publish',
            name='file',
        ),
        migrations.AddField(
            model_name='publish',
            name='jsonfile',
            field=models.FileField(default='', upload_to='media/files'),
        ),
        migrations.DeleteModel(
            name='UploadFile',
        ),
    ]
