# Generated by Django 2.2.16 on 2022-04-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packageAnalyse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['-id'], 'verbose_name': '模块大小记录表', 'verbose_name_plural': '模块大小记录表'},
        ),
        migrations.AlterModelOptions(
            name='publish',
            options={'ordering': ['-id'], 'verbose_name': '版本发布记录表', 'verbose_name_plural': '版本发布记录表'},
        ),
        migrations.AlterField(
            model_name='publish',
            name='result',
            field=models.FileField(upload_to='files'),
        ),
    ]
