# Generated by Django 2.2.16 on 2022-04-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packageAnalyse', '0002_auto_20220408_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='jsonfile',
            field=models.FileField(default='', upload_to='files'),
        ),
    ]
