# Generated by Django 2.2.16 on 2022-04-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packageAnalyse', '0003_auto_20220407_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to='media/files'),
        ),
    ]
